# Generated by Django 5.2.8 on 2025-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/team_default.png', upload_to='teams/logos/'),
        ),
    ]
