# Generated by Django 5.2.8 on 2025-11-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy'), ('woman', 'Woman'), ('man', 'Man'), ('other', 'Other')], max_length=10)),
                ('playing_position', models.CharField(choices=[('goal_shooter', 'Goal Shooter'), ('goal_attack', 'Goal Attack'), ('wing_attack', 'Wing Attack'), ('centre', 'Centre'), ('wing_defence', 'Wing Defence'), ('goal_defence', 'Goal Defence'), ('goal_keeper', 'Goal Keeper'), ('other', 'Other')], max_length=50)),
                ('photo', models.ImageField(default='defaults/player_default.png', upload_to='players/photos/')),
                ('institution_name', models.CharField(max_length=255)),
                ('registration_code', models.CharField(editable=False, max_length=4, unique=True)),
                ('consent_to_play', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournaments.team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
