# Generated by Django 5.2.8 on 2025-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/player_default.png', upload_to='players/photos/'),
        ),
    ]
